name: pulumi_random
version: 4.19.1
description: A Pulumi package to safely use randomness in Pulumi programs.
repository: https://github.com/pulumi/pulumi-random
homepage: https://pulumi.io

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  pulumi:
    path: ../../sdk/dart
  meta: ^1.11.0
  protobuf: ^6.0.0

dev_dependencies:
  test: ^1.25.0
  lints: ^3.0.0
